Core: Refactor ZOrderByteUtils
apache/iceberg pull request #10624
Opened 2024-07-03 12:58 UTC by ajantha-bhat

Follow up from https://github.com/apache/iceberg/pull/10583#discussion_r1660623439
Addressing my own comment. 

- Fix the java docs
- Update `intToOrderedBytes` to use `longToOrderedBytes`
- Use `longToOrderedBytes` for `shortToOrderedBytes` and `tinyintToOrderedBytes` to avoid double casting.

2024-07-03 12:59 UTC, ajantha-bhat commented
cc: @snazy, @nastra

2024-07-17 10:33 UTC, ajantha-bhat commented
ping: @nastra

2024-07-18 16:49 UTC, RussellSpitzer commented
I think this is generally fine, but I do think the internal methods being called should probably be renamed rather that continuing to use the "long" and "double" method names. 

for example having a 
"wholeNumberOrderedBytes"

and

"floatingPointOrderedBytes"

2024-07-31 07:32 UTC, ajantha-bhat commented
@RussellSpitzer: Thanks for the review. I have extracted the inner method as you suggested.

2024-08-01 05:31 UTC, ajantha-bhat commented
Failed due to flaky test: https://github.com/apache/iceberg/issues/10599

2024-08-01 13:59 UTC, RussellSpitzer approved these changes

2024-08-01 14:02 UTC, RussellSpitzer requested changes
Sorry, I missed that the java docs all need to be fixed now. They now reference things which aren't happening anymore. The implementation details should go in the doc for wholeNumberedOrderedBytes and FloatingPOintOrderedBytes

2024-09-02 13:28 UTC, ajantha-bhat commented
@RussellSpitzer: I have updated it today. Sorry for delay on this. I lost track of this PR notification.

2024-09-03 18:25 UTC, RussellSpitzer approved these changes

2024-09-03 18:25 UTC, RussellSpitzer commented
Thanks @ajantha-bhat , Merged

2024-09-03 18:25 UTC, merged