Move format docs to mkdocs from hugo and fix links
apache/iceberg pull request #9843
Opened 2024-03-01 06:12 UTC by bitsondatadev

Fixes #9842

2024-03-01 13:07 UTC, nastra commented on format/spec.md
> +1. The file system table scheme is implemented in [HadoopTableOperations](javadoc/latest/{{ icebergVersion }}/index.html?org/apache/iceberg/hadoop/HadoopTableOperations.html).
even when removing `icebergVersion`, this constructs a URL that is relative to the current page: 
`spec/javadoc/latest/index.html?org/apache/iceberg/hadoop/HadoopTableOperations.html`

2024-03-01 13:07 UTC, nastra requested changes
javadoc links aren't working, but the other changes look good

2024-03-01 15:52 UTC, bitsondatadev commented
lol I forgot this is from another directory higher than the docs...I know relative links are better in the long run but ugh they're a pain to debug in the beginning.

2024-03-02 20:35 UTC, bitsondatadev commented on format/spec.md
> +1. The file system table scheme is implemented in [HadoopTableOperations](javadoc/latest/{{ icebergVersion }}/index.html?org/apache/iceberg/hadoop/HadoopTableOperations.html).
just gonna fix the image first

2024-03-02 21:02 UTC, amogh-jahagirdar approved these changes

2024-03-02 21:03 UTC, amogh-jahagirdar commented
Discussed with @bitsondatadev right now we're aiming to get the image fixed first, that works for me locally.

2024-03-02 21:03 UTC, merged